### ISSUE TITLE
Errata for positive definite matrix in page 701

### ISSUE THREAD

**Issue by erdosxx** [yousuketakada/prml_errata#21]
In page 701, second paragraph, "A matrix A is said to be positive definite, denoted by A > 0, if w^TAw > 0 for all non-zero values of the vector w. Equivalently, a positive definite matrix has \lambda_i > 0 for all of its eigenvalues ..."  has some error as following.
The conditions in "Equivalently Equivalently, a positive definite matrix has \lambda_i > 0 for all of its eigenvalues ..." is  true only when A is "symmetric" positive definite matrix. That is not all positive definite matrix is symmetric. For example, 

\begin{pmatrix} 1 & 1 \\-1 & 1\end{pmatrix} is not symmetric but positive definite and does not have positive eigenvalues.
(As David Mitra showed in https://math.stackexchange.com/questions/83134/does-non-symmetric-positive-definite-matrix-have-positive-eigenvalues)

So, my suggestion to correct is "Equivalently, a positive definite matrix" --> "If A is a symmetric, positive definite matrix".

**Comment by yousuketakada** [comment]
Thank you for your suggestion; your argument totally makes sense.
However, I would suggest a different correction; see my comments below.

I suppose that, throughout the concerned section ``Eigenvector Equation'' beginning at page 698, A is assumed to be square (because eigen things make sense only for squre matrices), and, from the second paragraph at page 699, A is also assumed to be symmetric (although (C.47) and (C.48) hold for non-symmetric matrices as well).
So, it feels more consistent to me to correct as follows:

Page 701
Paragraph 2, Line 1: ``A matrix $\mathbf{A}$'' should read ``A symmetric matrix $\mathbf{A}$'' because we usually restrict positive definitness to symmetric matrices only (as assumed in this errata).

As you might have already noticed, a drawback of the above correction is that we should also correct (C.49):

Page 701
Equation (C.49) and the following line: To be consistent with our definition of positive definitness of a square matrix, we should give a symmetric matrix as an example of a non-definite matrix such that all the elements are positive. For instance, a symmetric matrix of the form
\begin{pmatrix}
1 & 2 \
2 & 1
\end{pmatrix}
has eigenvalues -1 and 3.

It might be helpful to also give an example of a positive-definite matrix such that some (non-diagonal) elements are negative, e.g., 
\begin{pmatrix}
1 & -2 \
-2 & 5
\end{pmatrix}
has positive eigenvalues.

**Comment by erdosxx** [comment]
I think that your comment is clear and consistent and can agree with you.
Thank you for you efforts to make PRML more clear. Your errata document is invaluable source to study PRML.
